% part 5: Compute the Fundamental matrix from known camera calibration parameters
% not complete for the epipolar keeps outside of images
v1 = load('Parameters_V1_1.mat').Parameters;
v2 = load('Parameters_V2_1.mat').Parameters;
points3d = load('mocapPoints3D.mat').pts3D;
image1 = imread('im1corrected.jpg');
image2 = imread('im2corrected.jpg');
addpath("./");

v1_Kmat = v1.Kmat;
v2_Kmat = v2.Kmat;
v1_Rmat = v1.Rmat;
v2_Rmat = v2.Rmat;
v1_position = v1.position(:);
v2_position = v2.position(:);


F = get_F_from_camera_calibration_parameters(v1_Rmat, v2_Rmat, v1_Kmat, v2_Kmat, v1_position, v2_position);

% Display the Fundamental matrix
fprintf('Fundamental Matrix F for task3.5:\n');
disp(F);

% Verfiy F
% Copy and adjust the code from eight point algorithm demo
num_points = size(points3d, 2);
v1_points2d = task3_2('Parameters_V1_1.mat', 'mocapPoints3D.mat', 'im1corrected.jpg', 0);
v2_points2d = task3_2('Parameters_V2_1.mat', 'mocapPoints3D.mat', 'im2corrected.jpg', 0);


display_epipolar_lines(F, v1_points2d, v2_points2d, image1, image2, "Graph about epipolar lines generated by F matrix, which generated by " + newline +"camera calibration parameters, ");
